processed 5 tasks

task 1 'run-graphql'. lines 6-28:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "HeJ4c5QyUwBD2fcg3uj5t1TtymBDJpxUNkkq3k7bne7o",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "HeJ4c5QyUwBD2fcg3uj5t1TtymBDJpxUNkkq3k7bne7o",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "HeJ4c5QyUwBD2fcg3uj5t1TtymBDJpxUNkkq3k7bne7o",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "HeJ4c5QyUwBD2fcg3uj5t1TtymBDJpxUNkkq3k7bne7o",
      "sequenceNumber": 0
    }
  }
}

task 2 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 4 'run-graphql'. lines 36-58:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "HeJ4c5QyUwBD2fcg3uj5t1TtymBDJpxUNkkq3k7bne7o",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "B9KFac6rzArgpD9aQoYSDnGAvKrFBqv2yRWb3xw7vmNa",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "HeJ4c5QyUwBD2fcg3uj5t1TtymBDJpxUNkkq3k7bne7o",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "B9KFac6rzArgpD9aQoYSDnGAvKrFBqv2yRWb3xw7vmNa",
      "sequenceNumber": 2
    }
  }
}
