processed 21 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-202:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "CuKiKrVGk7Pc9T7UmXQ4E8GqpvmhPnETiXhNVtEe4jjL",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AEOOPPvWlTDh16VWOe+Km0cHOQP8cFy+kRaaiMPSai3VBP7PWo8Sdr8AtpNHJR4rYPzGqhEyxgqP441uTJRcBgl/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "G3WP9VQgv2ixjoQMz8JAgevQeJdNEQLc9sXiCBf5FTW1"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7315600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                    "digest": "2RR1EATXMzXsM4vUhhtSzUdkwxF4VDNyBF8L5Hd37WtN"
                  }
                },
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                    "digest": "CZJB1dYDHCfrvPw3o9j1ZjwdboKoCVc5hrmv8iy9sL7A"
                  }
                },
                {
                  "address": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2",
                    "digest": "CcAhCEwCi5Y2THhU5FbHyr18kkGKcSfbT57gJDhpB6et"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CuKiKrVGk7Pc9T7UmXQ4E8GqpvmhPnETiXhNVtEe4jjL"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 204-222:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 224-224:
Checkpoint created: 2

task 6 'run-graphql'. lines 226-405:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "8xSqN47vWTco6mCkzfKygebuQs9PEYbzhbabmHpqsG1v",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "APgCYelf3C9TbwqkHjQE0ilCRUZHc5xZ3AShwq9hth41xMPNPNhvHMZob6GRvkweLoulKj9gBDPyuOyLl4M3Tg5/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                    "version": 2,
                    "digest": "2RR1EATXMzXsM4vUhhtSzUdkwxF4VDNyBF8L5Hd37WtN",
                    "object": {
                      "address": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                      "version": 2,
                      "digest": "2RR1EATXMzXsM4vUhhtSzUdkwxF4VDNyBF8L5Hd37WtN",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                            "package": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "CuKiKrVGk7Pc9T7UmXQ4E8GqpvmhPnETiXhNVtEe4jjL"
                },
                {
                  "digest": "G3WP9VQgv2ixjoQMz8JAgevQeJdNEQLc9sXiCBf5FTW1"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-4993420",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x292dd33e4555aee3e2cd66afdfda507a8981ab6ec6eaa6f2781b894a3fdebfbf",
                    "digest": "6m6XZvikRjR564D56FxySBhn9HYHdBaQRKRhpVBKAA8Y"
                  }
                },
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                    "digest": "8VCkkQna5PFhCiT4qewco6XTojiWNssYDrex9tyVSM4k"
                  }
                },
                {
                  "address": "0xd2c5b6664f91426d27a9d5cd72c0ec150ef754720f1866ca5a434daa164809aa",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd2c5b6664f91426d27a9d5cd72c0ec150ef754720f1866ca5a434daa164809aa",
                    "digest": "D2r7D7CrJ464hEJmHLETrDpicDvxQYMS47AfQ52uSv8u"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "8xSqN47vWTco6mCkzfKygebuQs9PEYbzhbabmHpqsG1v"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 407-410:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 412-421:
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'create-checkpoint'. lines 423-423:
Checkpoint created: 3

task 10 'run-graphql'. lines 425-613:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9G6DYhuSs5rhz9sMBCg58GaWNxUWcCADhBK3ZzJ5vQdc",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ANf3AMictsRzZsZHJLlBw62+Eah8cOgUpXbmg1WQDTbvoV4srM86yzq10kgx7tUJgUH8ohCrBJ6Jhjb0/sc+Xgx/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xd2c5b6664f91426d27a9d5cd72c0ec150ef754720f1866ca5a434daa164809aa",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xd2c5b6664f91426d27a9d5cd72c0ec150ef754720f1866ca5a434daa164809aa",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xd2c5b6664f91426d27a9d5cd72c0ec150ef754720f1866ca5a434daa164809aa",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "8xSqN47vWTco6mCkzfKygebuQs9PEYbzhbabmHpqsG1v"
                },
                {
                  "digest": "Cp6AHYTf5A5XW83vW1GHWDyVp1Wbz8HoVdzLjaX1KGWN"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3350680",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                    "digest": "2kpFFwBsKozsJfN5Rq9kNgomfXLSy92m8VVvGuZy67R1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                          "balance": {
                            "value": "299999982036420"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xa783d73fab6e4caf87632f3b11d145eb9cf5a694dcd3cd67cc621576d56cddc9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xa783d73fab6e4caf87632f3b11d145eb9cf5a694dcd3cd67cc621576d56cddc9",
                    "digest": "3tH1Sr5na8bcDdqJgpzm4Dp3e7QdNE85fvktELubnJcn",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xa783d73fab6e4caf87632f3b11d145eb9cf5a694dcd3cd67cc621576d56cddc9",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xf11555a25fb5a56d47278bce2109426a08649be055a61673639e7c51880f68ef",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xf11555a25fb5a56d47278bce2109426a08649be055a61673639e7c51880f68ef",
                    "digest": "AAfPsCTmGMWSZyqxDnviafdf35FrosKK9DvS9rPCgXD6",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x59835379b4103b7451a65cfa4c8bdddc6ee1620d4af30ed93e7a8979733f68d2::m::Foo"
                        },
                        "json": {
                          "id": "0xf11555a25fb5a56d47278bce2109426a08649be055a61673639e7c51880f68ef",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "9G6DYhuSs5rhz9sMBCg58GaWNxUWcCADhBK3ZzJ5vQdc"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11 'programmable'. lines 615-616:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12 'create-checkpoint'. lines 618-618:
Checkpoint created: 4

task 13 'run-graphql'. lines 620-799:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "7eu9bCqKLvhjGPm2LDxMgp2Yo9mx79QtoaeaeCvTxuNZ",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ABoiGbYFxdKKqBd3o/j6xAS4AuMTmX3G5Fd2T1lxXXXRlxXQo0Sg8V9u/gLs7wsN7q+RJHWPAMSZzypG+8fHlAJ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "9G6DYhuSs5rhz9sMBCg58GaWNxUWcCADhBK3ZzJ5vQdc"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1009880",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f",
                    "digest": "5Ev9X35X6vGquyzGXesEnvVPSG4VA8wBVmsYn864rbVa"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x2f0e8ce087e32004019169106e6353d81261393080029a9f4aacfc0d216eca5f"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "7eu9bCqKLvhjGPm2LDxMgp2Yo9mx79QtoaeaeCvTxuNZ"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 801-811:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowfQ",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 813-823:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowfQ",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 825-835:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17 'run-graphql'. lines 837-844:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18 'run-graphql'. lines 846-851:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyfQ"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ"
        }
      ]
    }
  }
}

task 19 'run-graphql'. lines 853-858:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0fQ"
        }
      ]
    }
  }
}

task 20 'run-graphql'. lines 860-870:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ"
        }
      ]
    }
  }
}
