processed 21 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-202:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "BZqSEP9auUJ6BxjMbt7BGx2xt7nnLSL35B9MCyF9nfdS",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AEcFfH1RHoL4YO41o0Jy1FGXDLzLByA5eNPza8ZGUEUsWYbk6F++xT8nkD1Dscyg0eppFmPjIn50U+F6UTa24wZ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "HbP4QGFcVNGCdSRsx6P8voHDAbjKuGaiR5VEpfjpxtd6"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7315600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                    "digest": "CQZQudekM4QzBYCqUgRgnY9k25jxepEnRH9e3EQmnsyR"
                  }
                },
                {
                  "address": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                    "digest": "2H9C7nFNCdtfVzGkXWz7eYJNJg2oCQxqrRPC8PTn3dyg"
                  }
                },
                {
                  "address": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a",
                    "digest": "EaXKjGKCupg6VMAoTVPphm4sXTCjJRVNGuZ8wDNgxWi1"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "BZqSEP9auUJ6BxjMbt7BGx2xt7nnLSL35B9MCyF9nfdS"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 204-222:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 224-224:
Checkpoint created: 2

task 6 'run-graphql'. lines 226-405:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "8PCBqn6Pk5xW9foL7tXiiRQmoGC5D3tCRmo8BTeWM8sa",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AJwTaS7I0xCvmqKKWyBfFqCbdxIANX0qPVZZyzVlUFenqmD3+XcL2xTqSVma5vh2mfMYaLOL+F3K+lSOl/qVEgh/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                    "version": 2,
                    "digest": "2H9C7nFNCdtfVzGkXWz7eYJNJg2oCQxqrRPC8PTn3dyg",
                    "object": {
                      "address": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                      "version": 2,
                      "digest": "2H9C7nFNCdtfVzGkXWz7eYJNJg2oCQxqrRPC8PTn3dyg",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                            "package": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "BZqSEP9auUJ6BxjMbt7BGx2xt7nnLSL35B9MCyF9nfdS"
                },
                {
                  "digest": "HbP4QGFcVNGCdSRsx6P8voHDAbjKuGaiR5VEpfjpxtd6"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-4993420",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                    "digest": "2f6vRcpYqcmsSUvyzNfMf9Mo5yDJXQS1ibvupWW9uLiu"
                  }
                },
                {
                  "address": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x92dd102257a3e2472973c45788b2e7b5b3e130d68c9e9a3b414024aa6f77c909",
                    "digest": "GSnnPdFxUFG2ABAAsbkKyQ9NygLrPJbKr16UdwksSYZ7"
                  }
                },
                {
                  "address": "0xd302d530bd895570efe20508adf08418f5b03eed1651b2cdd58d9a7e49eaf9d8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd302d530bd895570efe20508adf08418f5b03eed1651b2cdd58d9a7e49eaf9d8",
                    "digest": "8UMPuUN7q44ZCCsLrNoWsGcWhJjjfDAcMAoM3wowhVqS"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "8PCBqn6Pk5xW9foL7tXiiRQmoGC5D3tCRmo8BTeWM8sa"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 407-410:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 412-421:
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'create-checkpoint'. lines 423-423:
Checkpoint created: 3

task 10 'run-graphql'. lines 425-613:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "Hy9WDQbLZDS4DNPw7j9A7g33TS2KkBCpKeoX1Vrfpdc8",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AJ5Hsnj5XFSx0ygxGobYEQm+PzGC83oBH6F5HHkoTv+9FC+K5CGBUw3CfdEFniNsr1NfBvlI/ij2UWTLaaYkkgN/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xd302d530bd895570efe20508adf08418f5b03eed1651b2cdd58d9a7e49eaf9d8",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xd302d530bd895570efe20508adf08418f5b03eed1651b2cdd58d9a7e49eaf9d8",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xd302d530bd895570efe20508adf08418f5b03eed1651b2cdd58d9a7e49eaf9d8",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "6jN35UbVKj1RTLY2cXVoGzNWVBvQJ6wKUxEC5TNDU1NM"
                },
                {
                  "digest": "8PCBqn6Pk5xW9foL7tXiiRQmoGC5D3tCRmo8BTeWM8sa"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3350680",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                    "digest": "2bYYs92wph5T5SqKKSFU5YXg3kWa7Uj7hLdT3aVrv7pz",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                          "balance": {
                            "value": "299999982036420"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x4fd6661fdd341108e8e90b8b0646b542b5d25efade25203ace9e3760b1cd4733",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4fd6661fdd341108e8e90b8b0646b542b5d25efade25203ace9e3760b1cd4733",
                    "digest": "Bqk9zF6RGxJ3enmLxk96iCCxukJXJKcAqCYcVePyDaMR",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xad613455574ac6fcc7b292b3dc3828cadc30ae8c20018aecdb454c9d51845d3a::m::Foo"
                        },
                        "json": {
                          "id": "0x4fd6661fdd341108e8e90b8b0646b542b5d25efade25203ace9e3760b1cd4733",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xaa4f523191a03ecf6565793f34b6743bd097db300821758104be65a43b3c419a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xaa4f523191a03ecf6565793f34b6743bd097db300821758104be65a43b3c419a",
                    "digest": "FLRetJBMTbhQ71rGZmehkPbhbz48BEtepB4Tt1wrSt1n",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xaa4f523191a03ecf6565793f34b6743bd097db300821758104be65a43b3c419a",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "Hy9WDQbLZDS4DNPw7j9A7g33TS2KkBCpKeoX1Vrfpdc8"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11 'programmable'. lines 615-616:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12 'create-checkpoint'. lines 618-618:
Checkpoint created: 4

task 13 'run-graphql'. lines 620-799:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "FkDFhcrtvdZbm5csn9NSHADdg7CoNof523h8mZkvYX3v",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AG+dAmABILCqDyDI7+FMLo8r65Yg6ivp+wArs2hlP94Ul4qQrM6nOaIWkyg08PZMd/2QVfTUa7KmqiwJX2U1tQR/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "Hy9WDQbLZDS4DNPw7j9A7g33TS2KkBCpKeoX1Vrfpdc8"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1009880",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9",
                    "digest": "HvL24yxib3bwbAkhjRJDKYHh7yF8JEgZEACJSXbrzK6j"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x4c8f28a346ba2f85df4b81efa6f8ec6de0f793bc6d9493afa4acdf583835c9b9"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "FkDFhcrtvdZbm5csn9NSHADdg7CoNof523h8mZkvYX3v"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 801-811:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJ0YyI6MH0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJ0YyI6MX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJ0YyI6NH0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 813-823:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJ0YyI6MH0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 825-835:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJ0YyI6MX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJ0YyI6NH0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17 'run-graphql'. lines 837-844:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18 'run-graphql'. lines 846-851:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        }
      ]
    }
  }
}

task 19 'run-graphql'. lines 853-858:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30"
        }
      ]
    }
  }
}

task 20 'run-graphql'. lines 860-870:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        }
      ]
    }
  }
}
