processed 7 tasks

task 1 'publish'. lines 6-26:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 31-32:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 4 'programmable'. lines 34-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 5 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 6 'run-graphql'. lines 40-88:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x4523af535853acb736b28ca704c004d07ef308d486098f2740332c4c9d12c51e",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0x5014aa73a2cb313e175d4deea1671eb5cacf7b0901bea86947c1d24b76d22a02",
                  "version": 2,
                  "digest": "68SKAyua2aQ14ruZBiTM5bQxNJk3n6z3TNZ88HzwX3WU",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x4523af535853acb736b28ca704c004d07ef308d486098f2740332c4c9d12c51e::m::Foo"
                        },
                        "json": {
                          "id": "0x5014aa73a2cb313e175d4deea1671eb5cacf7b0901bea86947c1d24b76d22a02",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x4523af535853acb736b28ca704c004d07ef308d486098f2740332c4c9d12c51e",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x4523af535853acb736b28ca704c004d07ef308d486098f2740332c4c9d12c51e",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0x4523af535853acb736b28ca704c004d07ef308d486098f2740332c4c9d12c51e",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
