processed 8 tasks

task 1 'run-graphql'. lines 8-102:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "35Nte7ec9deL26XNoHnNzhfHRF7c6SUZdeTMLXkTXGCd",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZ3JvdGgxNiIsImMiOjB9",
                            "node": {
                              "name": "groth16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZ3JvdXBfb3BzIiwiYyI6MH0",
                            "node": {
                              "name": "group_ops"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2Vfc3Vic2lkeSIsImMiOjB9",
                            "node": {
                              "name": "stake_subsidy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "sui_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "sui_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0xd34864e019e2c76461849fbf22270202b5b30f9b26d879bc0d77e1c025384a6a",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x642cc0ed9b580342702fad425888dcc6e7c78bd9d733b8ad8c0681385bc9d2b2",
                            "size": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiY2xvYiIsImMiOjB9",
                            "node": {
                              "name": "clob"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvYl92MiIsImMiOjB9",
                            "node": {
                              "name": "clob_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3JpdGJpdCIsImMiOjB9",
                            "node": {
                              "name": "critbit"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuIiwiYyI6MH0",
                            "node": {
                              "name": "custodian"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuX3YyIiwiYyI6MH0",
                            "node": {
                              "name": "custodian_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWF0aCIsImMiOjB9",
                            "node": {
                              "name": "math"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3JkZXJfcXVlcnkiLCJjIjowfQ",
                            "node": {
                              "name": "order_query"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x02698d1ce944692d2a43587ea01a7e9b2e716b544a703333d9108200a19ebbee",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0x02698d1ce944692d2a43587ea01a7e9b2e716b544a703333d9108200a19ebbee",
                          "authorizer_validator_address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x1cba807fb1e0b3a6479421c171560068ab970d2fb4f700e11cb6abf1cfb3c0e7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0x1cba807fb1e0b3a6479421c171560068ab970d2fb4f700e11cb6abf1cfb3c0e7",
                          "name": "0",
                          "value": {
                            "sui_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x5d06525b0d786d4dbbeeea483a8f655a708ed818b1fc5278135f0dddc70ea563",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x5d06525b0d786d4dbbeeea483a8f655a708ed818b1fc5278135f0dddc70ea563",
                          "name": "0x42af06da95d7e7418673efebcb3d7df8ee9a419398d3fc449d605c7573a4013d",
                          "value": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "38",
                            "system_state_version": "1",
                            "validators": {
                              "total_stake": "20000000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "sui_address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                                    "protocol_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "worker_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      128,
                                      156,
                                      67,
                                      33,
                                      58,
                                      1,
                                      39,
                                      117,
                                      201,
                                      238,
                                      255,
                                      186,
                                      75,
                                      160,
                                      126,
                                      112,
                                      202,
                                      232,
                                      153,
                                      37,
                                      253,
                                      202,
                                      71,
                                      140,
                                      94,
                                      117,
                                      125,
                                      17,
                                      181,
                                      101,
                                      235,
                                      149,
                                      12,
                                      103,
                                      135,
                                      36,
                                      124,
                                      64,
                                      40,
                                      191,
                                      203,
                                      204,
                                      20,
                                      212,
                                      46,
                                      230,
                                      32,
                                      74
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                    "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_worker_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "next_epoch_worker_address": null,
                                    "extra_fields": {
                                      "id": "0xe7e4edd5899d7202c65c2557a44be1c4883a51acaaaa88e0a13fd1237449bd16",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0x02698d1ce944692d2a43587ea01a7e9b2e716b544a703333d9108200a19ebbee",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x42af06da95d7e7418673efebcb3d7df8ee9a419398d3fc449d605c7573a4013d",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "sui_balance": "20000000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "20000000000000000",
                                    "exchange_rates": {
                                      "id": "0x795c6fa26728a580252ff4c218cfa2d17f29910e6e40d9f3df2d924483a408c2",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_sui_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0xee78a4b00099d642ddf617582f7ac621b2fefb23112a6914d358f907466a3a5b",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "20000000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xd9fb20ae36dda178e38b3192cf4caccc78f4d3e8b53275bad711856eb269aa6c",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0xd383149f2642cf5e360ea1430518ab0637513fbea84ac91f47d25df919e76d46",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0xe50c91330e5c80f85caff0e9e6dcba133112a0100896d51c1061c31076d11d21",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0x4043708771fa5c22dff5df8326061dbbe223866e00f70ea76e4cf98cd802ddfe",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0x482d72fcf9a699864caeb3b0e0f6d696b89237c13b84dad0d468e0ce327f9a31",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x7238ae40abad7858df2adeb4eb8507f14c6837ccf4d0b455b1790c14bc3505bf",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "stake_subsidy_start_epoch": "0",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "30000000000000000",
                              "validator_low_stake_threshold": "20000000000000000",
                              "validator_very_low_stake_threshold": "15000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0xa972605fb431e1b2fa58aa1be913199937b938c2e21d4e8ca8ea82c1e6c5296f",
                                "size": "0"
                              }
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "stake_subsidy": {
                              "balance": {
                                "value": "9949700000000000000"
                              },
                              "distribution_counter": "0",
                              "current_distribution_amount": "1000000000000000",
                              "stake_subsidy_period_length": "10",
                              "stake_subsidy_decrease_rate": 1000,
                              "extra_fields": {
                                "id": "0xdf50dd690cc33ccd1c3fff0b1dbb52acb7f993161c72d6f9ad9805f1d6450860",
                                "size": "0"
                              }
                            },
                            "safe_mode": false,
                            "safe_mode_storage_rewards": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0x544d6060705c5aee1a22e76b868f931c561268dd034de02c2b99ed280a33186e",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x7c55a339c72e0fa55d9acbff8ed3606d95ab0c208b0fe2627dd90ed095444f59",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                        },
                        "json": {
                          "id": "0x7c55a339c72e0fa55d9acbff8ed3606d95ab0c208b0fe2627dd90ed095444f59",
                          "pool_id": "0x42af06da95d7e7418673efebcb3d7df8ee9a419398d3fc449d605c7573a4013d",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "20000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x8465f001d2df0d096cd4ce39f88780aa07eee56b2f9850e8ead11635bcd9ef48",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x8465f001d2df0d096cd4ce39f88780aa07eee56b2f9850e8ead11635bcd9ef48",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                        },
                        "json": {
                          "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "active_jwks": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0xd14908f6a7b873db522d879673c3e1bbff9f95e153f56dd774dd5ebca668f8d7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::PerTypeList>"
                        },
                        "json": {
                          "id": "0xd14908f6a7b873db522d879673c3e1bbff9f95e153f56dd774dd5ebca668f8d7",
                          "name": "0",
                          "value": {
                            "id": "0xd63094121d75682a3f06892c241989d5f6df9d742fa76ee15ea949465b58b89b",
                            "denied_count": {
                              "id": "0xc517572ecfe996a1d6c4163fc0b882d1a9f8948af308f4559e83d899e706a333",
                              "size": "0"
                            },
                            "denied_addresses": {
                              "id": "0x6637f711ffd7f66a8a742d3da468c50aa606981bdc1ef73aaa348ae6acdd27cc",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0xd425c63eebe3867d8bca99b2863fd8dea682e7b5e55c60b4e098c854982914f0",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xd425c63eebe3867d8bca99b2863fd8dea682e7b5e55c60b4e098c854982914f0",
                          "decimals": 9,
                          "name": "Sui",
                          "symbol": "SUI",
                          "description": "",
                          "icon_url": null
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0xd6df54347a916e7f700223cd0e6785c15ada0c9754a752ba249765bba45e63f1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xd6df54347a916e7f700223cd0e6785c15ada0c9754a752ba249765bba45e63f1",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0xeb2f8382ec04d5ed03425dd3bffa7a62870a4c8122873a527f45147d5fa11144",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0xeb2f8382ec04d5ed03425dd3bffa7a62870a4c8122873a527f45147d5fa11144",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                },
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "H5AY5Sa8hkpDvReMDWG7uwiUnWQiFXDWiVUK1p7i2YT2"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "Cup7uY7RPePamJ95JF5Dz6xbTCSme9cGHMYY59SbgTaR"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "6eHqU5Ckttz1ergEMxjapvZjPAoFRQH9vjg4ksUf6G4S"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "GjqLB2rpUXppXi3T7GyRNBm7F69H1sd1D5oG1EFCTrkd"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "FUxQ9VcromRetQeZXrEJrtLu1GVKhhUobkviJH3wvBHZ"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "digest": "4zJGnS9mfrFeAW8dD63jUe6n5UjVbvFNmF6Qx3syk4eC"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "3hTuzTQz41PvWMyzjfBgqSABzm9b9cbvKGEzRfberJ4G"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "EhobdsDWeGHvsj2i58hX2G5LLjjUqfuW5iUmBMb8aKJw"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "digest": "AsmxpXkd8R5i5mg1Dfb9CGNun6CmnqDRAoHcbgho5opv"
                  }
                },
                {
                  "address": "0x02698d1ce944692d2a43587ea01a7e9b2e716b544a703333d9108200a19ebbee",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x02698d1ce944692d2a43587ea01a7e9b2e716b544a703333d9108200a19ebbee",
                    "digest": "FB7nF5L3edeY5fNqfbaBcz1R4DeDnbxbVrMkQacfiuNZ"
                  }
                },
                {
                  "address": "0x1cba807fb1e0b3a6479421c171560068ab970d2fb4f700e11cb6abf1cfb3c0e7",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1cba807fb1e0b3a6479421c171560068ab970d2fb4f700e11cb6abf1cfb3c0e7",
                    "digest": "Hvxgoij11H8yE971tpq5nVbRKbnZHEyxY8Ufkawvgftx"
                  }
                },
                {
                  "address": "0x5d06525b0d786d4dbbeeea483a8f655a708ed818b1fc5278135f0dddc70ea563",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5d06525b0d786d4dbbeeea483a8f655a708ed818b1fc5278135f0dddc70ea563",
                    "digest": "JE3W6XqbiAPStCPfyGWnZyWobNbGB5ShBu2rKYhDjHhS"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "BurqN7hFcM1KSBaDSVejQxPNwBHYXu5bihcw6DvCPP1K"
                  }
                },
                {
                  "address": "0x7c55a339c72e0fa55d9acbff8ed3606d95ab0c208b0fe2627dd90ed095444f59",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x7c55a339c72e0fa55d9acbff8ed3606d95ab0c208b0fe2627dd90ed095444f59",
                    "digest": "Gxeyb7N3AHzjpf1h21KUHuJ6MtXak8oDGHPBJzehTvXt"
                  }
                },
                {
                  "address": "0x8465f001d2df0d096cd4ce39f88780aa07eee56b2f9850e8ead11635bcd9ef48",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x8465f001d2df0d096cd4ce39f88780aa07eee56b2f9850e8ead11635bcd9ef48",
                    "digest": "S5fHDz1W485qf4L7TqFse7jdXYcMCtZfyE381zWhX5b"
                  }
                },
                {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                    "digest": "GA57hnsPZRHE1xHdW7voNkfnyZXkVtma7h5ZKhUrQpxC"
                  }
                },
                {
                  "address": "0xd14908f6a7b873db522d879673c3e1bbff9f95e153f56dd774dd5ebca668f8d7",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd14908f6a7b873db522d879673c3e1bbff9f95e153f56dd774dd5ebca668f8d7",
                    "digest": "4ZanoEHNvPhqsdhEjMjxKr54TxVyZK6BJ6qr61TSidF1"
                  }
                },
                {
                  "address": "0xd425c63eebe3867d8bca99b2863fd8dea682e7b5e55c60b4e098c854982914f0",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd425c63eebe3867d8bca99b2863fd8dea682e7b5e55c60b4e098c854982914f0",
                    "digest": "9fPBzao2aT4LrVCAnTtYwMDhBSvTDjo3hsP19ShMue56"
                  }
                },
                {
                  "address": "0xd6df54347a916e7f700223cd0e6785c15ada0c9754a752ba249765bba45e63f1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd6df54347a916e7f700223cd0e6785c15ada0c9754a752ba249765bba45e63f1",
                    "digest": "Hx6YMEikbowMTnehhM9sqHp7FVcdBcWDw8njhVy71gWC"
                  }
                },
                {
                  "address": "0xeb2f8382ec04d5ed03425dd3bffa7a62870a4c8122873a527f45147d5fa11144",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xeb2f8382ec04d5ed03425dd3bffa7a62870a4c8122873a527f45147d5fa11144",
                    "digest": "6hA6bxS4waxbqpaaiaLGpE5bEPnAzFJAtWvh6itx5jnq"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "35Nte7ec9deL26XNoHnNzhfHRF7c6SUZdeTMLXkTXGCd"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 106-106:
Checkpoint created: 1

task 4 'run-graphql'. lines 108-183:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "35Nte7ec9deL26XNoHnNzhfHRF7c6SUZdeTMLXkTXGCd"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 187-187:
Epoch advanced: 0

task 7 'run-graphql'. lines 189-276:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9RJkHDq2KNvb6utbcqaY7BMJQ6Fw8HBnshi8z53dVman",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 38,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "35Nte7ec9deL26XNoHnNzhfHRF7c6SUZdeTMLXkTXGCd"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "9Ke6cgqonjWKvYhH7ap2Wy6QoeAvXztswWrNyJnd9pLG"
                  }
                },
                {
                  "address": "0x33d8782806c80b64429308717b762b03c6c3e2c6be7702ca7854ba1ff24877ed",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x33d8782806c80b64429308717b762b03c6c3e2c6be7702ca7854ba1ff24877ed",
                    "digest": "7vEY6GYS3q8WroFazBBRHe47RY8gEWUwf61CXBMinGd2"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "9Ac53tcPyCA3zKG6LqsqKLohAYx45biUeWSs4v311jRd"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": true,
                  "outputState": null
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "9RJkHDq2KNvb6utbcqaY7BMJQ6Fw8HBnshi8z53dVman"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
