processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-41:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 3 'programmable'. lines 45-47:
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4 'create-checkpoint'. lines 49-49:
Checkpoint created: 2

task 5 'run-graphql'. lines 51-92:
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6 'run-graphql'. lines 94-135:
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'transfer-object'. lines 137-137:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 8 'transfer-object'. lines 139-139:
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9 'create-checkpoint'. lines 141-141:
Checkpoint created: 3

task 10 'run-graphql'. lines 143-196:
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'create-checkpoint'. lines 200-200:
Checkpoint created: 4

task 14 'create-checkpoint'. lines 204-204:
Checkpoint created: 5

task 16 'create-checkpoint'. lines 208-208:
Checkpoint created: 6

task 17 'run-graphql'. lines 210-251:
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPQDvjYCZzHJRh2mFv/rx/evEQtvYoT2jXl3L5ZnaAfgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf403be36026731c9461da616ffebc7f7af110b6f6284f68d79772f96676807e0",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IDtg91jbaTSxyPhxx5FERDiP6O+8SbQCIyd9bLPCE4UaAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b60f758db6934b1c8f871c7914444388fe8efbc49b40223277d6cb3c213851a",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IFJdAWDgPe8RNkn2jhzPNJrpvm22w+25nzDETl/PHuRSAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x525d0160e03def113649f68e1ccf349ae9be6db6c3edb99f30c44e5fcf1ee452",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18 'force-object-snapshot-catchup'. lines 253-253:
Objects snapshot updated to [0 to 4)

task 19 'create-checkpoint'. lines 255-255:
Checkpoint created: 7

task 20 'run-graphql'. lines 257-286:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
