processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-42:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 44-44:
Checkpoint created: 1

task 3 'programmable'. lines 46-48:
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 5 'run-graphql'. lines 52-93:
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6 'run-graphql'. lines 95-136:
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'transfer-object'. lines 138-138:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 8 'transfer-object'. lines 140-140:
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9 'create-checkpoint'. lines 142-142:
Checkpoint created: 3

task 10 'run-graphql'. lines 144-197:
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'create-checkpoint'. lines 201-201:
Checkpoint created: 4

task 14 'create-checkpoint'. lines 205-205:
Checkpoint created: 5

task 16 'create-checkpoint'. lines 209-209:
Checkpoint created: 6

task 17 'run-graphql'. lines 211-252:
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMwL4HKNOWmzg77+HDAZQB9xvYu5A/DClYA152OeMnA+AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xcc0be0728d3969b383befe1c3019401f71bd8bb903f0c2958035e7639e32703e",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IBJCFxnvZ+VEx+Gx19qYzpU8DKoHAn6q+wwI3NFEATdJAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x12421719ef67e544c7e1b1d7da98ce953c0caa07027eaafb0c08dcd144013749",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEIptHEa+4AyHy3eLbi3bKCHqYh+dftq3z0lsYBPcZo4AQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4229b4711afb80321f2dde2db8b76ca087a9887e75fb6adf3d25b1804f719a38",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18 'force-object-snapshot-catchup'. lines 254-254:
Objects snapshot updated to [0 to 4)

task 19 'create-checkpoint'. lines 256-256:
Checkpoint created: 7

task 20 'run-graphql'. lines 258-287:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
