processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-31:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5456800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 33-33:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 35-35:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 37-37:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 5 'create-checkpoint'. lines 39-39:
Checkpoint created: 1

task 6 'run-graphql'. lines 41-69:
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'run'. lines 71-71:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 8 'create-checkpoint'. lines 73-73:
Checkpoint created: 2

task 9 'run-graphql'. lines 75-104:
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 106-181:
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "200"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0xf887cd3a368c6a5590845f2163c628c15518c818a1da99f7b3ff2746845b2ee9",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
                        },
                        "json": {
                          "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
                        },
                        "json": {
                          "id": "0xf887cd3a368c6a5590845f2163c628c15518c818a1da99f7b3ff2746845b2ee9",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run'. lines 183-183:
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 12 'create-checkpoint'. lines 185-185:
Checkpoint created: 3

task 13 'run-graphql'. lines 187-250:
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
                        },
                        "json": {
                          "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
                        },
                        "json": {
                          "id": "0xf887cd3a368c6a5590845f2163c628c15518c818a1da99f7b3ff2746845b2ee9",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 14 'run-graphql'. lines 252-327:
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "200"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0xf887cd3a368c6a5590845f2163c628c15518c818a1da99f7b3ff2746845b2ee9",
                "value": "300"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
              },
              "json": {
                "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
                        },
                        "json": {
                          "id": "0x6ef39443b76ccf073ffb5b49dec43fa1f7a42879541a6c8164f7fdfe9e08ae94",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xb4e9d7738bfa0ec7bf1a4f79ce8f207917148d4e6d570e7753eef2e713ee29ba::M1::Object"
                        },
                        "json": {
                          "id": "0xf887cd3a368c6a5590845f2163c628c15518c818a1da99f7b3ff2746845b2ee9",
                          "value": "300"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}
