processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-38:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 40-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 4 'programmable'. lines 45-48:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 6 'programmable'. lines 52-56:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 58-58:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 62-62:
Checkpoint created: 4

task 10 'run-graphql'. lines 64-138:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                "value": "4"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                "value": "2"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                "value": "5"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                "value": "3"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                "value": "200"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                "value": "6"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9a4756aa09d31354e19bc52598ac9602622073dcdb5317ea98069adc17fe3605",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 140-184:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9a4756aa09d31354e19bc52598ac9602622073dcdb5317ea98069adc17fe3605",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9a4756aa09d31354e19bc52598ac9602622073dcdb5317ea98069adc17fe3605",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9a4756aa09d31354e19bc52598ac9602622073dcdb5317ea98069adc17fe3605",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 186-186:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 188-188:
Checkpoint created: 5

task 14 'run-graphql'. lines 190-264:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                "value": "4"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                "value": "2"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                "value": "5"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                "value": "3"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                "value": "200"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                "value": "6"
              },
              "type": {
                "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9a4756aa09d31354e19bc52598ac9602622073dcdb5317ea98069adc17fe3605",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 266-266:
Checkpoint created: 6

task 16 'run-graphql'. lines 268-303:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d4b03527a254beddc7b5ba2611edf29c81f7082e580a473d0d51d17172a7f44",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x555444371cfc4f4f0ff0b01369832863d868f7d654f75b148e88ce93b95a38a2",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc9b291833548b496a69670c0fd5fb717529adb56544482a189c43a0a2936b9db",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd2c50d24697cdbcb842e5de43d5324c75fbfeab32217a2a8668c0d29d1d8e6f0",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xea4cd9952f869a1835b85d621737dac94229b939e0bf86f0d316bdabe0320eab",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf8af35c80d48e39e0573b907b3f43ff705d03af4b25d8e9b9d97b8344a0e80ae",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xa0432e2e44a7825c628721f41ee99187198d76f9ad5a7f8294caf68b25a1fb91::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
