processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-38:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 40-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 4 'programmable'. lines 45-48:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 6 'programmable'. lines 52-56:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 58-58:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 62-62:
Checkpoint created: 4

task 10 'run-graphql'. lines 64-138:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                "value": "3"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                "value": "5"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                "value": "200"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                "value": "2"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                "value": "6"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                "value": "4"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9745fc32da697aaa0c5a03d734810dde228035783ec0e1a48bc67ca62bd722a1",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 140-184:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9745fc32da697aaa0c5a03d734810dde228035783ec0e1a48bc67ca62bd722a1",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9745fc32da697aaa0c5a03d734810dde228035783ec0e1a48bc67ca62bd722a1",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9745fc32da697aaa0c5a03d734810dde228035783ec0e1a48bc67ca62bd722a1",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 186-186:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 188-188:
Checkpoint created: 5

task 14 'run-graphql'. lines 190-264:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                "value": "3"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                "value": "5"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                "value": "200"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                "value": "2"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                "value": "6"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                "value": "4"
              },
              "type": {
                "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9745fc32da697aaa0c5a03d734810dde228035783ec0e1a48bc67ca62bd722a1",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 266-266:
Checkpoint created: 6

task 16 'run-graphql'. lines 268-303:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x166da4eb6f010a00d8060bb865ade7231fbbd1771cb902be9a32dd646e4cbf6d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a3eeea0a9999ded15c970256d1ec74f53652a254315dbfb533261308d0ca69a",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x360176bbdab3e6116bd85828b949eccab234a996b7535317a614d493ac946166",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4d9ab80a2e57e36cfa4aabdac40c92c69d8a8cc3423df7f995e9d67a32ebbd2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8d924bf839e6cb960e3ee6b1d51d9375d73789ea68107766509de5234b258b43",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9f0f3f3838384ee555a8a731fba67179999c057f1290349fd402a3842add7331",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5599cc995484b6e01049b1f684e810cc71e3365ed7f5df55d0c8bf835d43d414::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
