processed 25 tasks

init:
validator_0: object(0,0)

task 1 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 30-30:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 32-32:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 34-34:
Owner: Account Address ( validator_0 )
Version: 1
Contents: sui_system::validator_cap::UnverifiedValidatorOperationCap {id: sui::object::UID {id: sui::object::ID {bytes: fake(0,0)}}, authorizer_validator_address: validator_0}

task 5 'view-object'. lines 36-36:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 6 'view-object'. lines 38-38:
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}, value: 0u64}

task 7 'create-checkpoint'. lines 40-40:
Checkpoint created: 4

task 8 'view-checkpoint'. lines 42-42:
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, storage_cost: 10176400, storage_rebate: 1956240, non_refundable_storage_fee: 19760 }}

task 9 'advance-epoch'. lines 44-44:
Epoch advanced: 5

task 10 'view-checkpoint'. lines 46-46:
CheckpointSummary { epoch: 5, seq: 10, content_digest: 56VgdXkQraGfoB4PxhzTEB4uVJkrTdjobvW2w4MeH8qC,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11 'run-graphql'. lines 48-53:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12 'create-checkpoint'. lines 55-55:
Checkpoint created: 11

task 13 'view-checkpoint'. lines 57-57:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14 'run-graphql'. lines 59-64:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15 'run-graphql'. lines 66-71:
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-sui-rpc-version": "2024.2.0",
    "access-control-allow-origin": "*",
    "vary": "origin",
    "vary": "access-control-request-method",
    "vary": "access-control-request-headers",
}
Service version: 2024.2.0
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16 'view-checkpoint'. lines 73-73:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17 'advance-epoch'. lines 75-78:
Epoch advanced: 6

task 18 'run-graphql'. lines 80-95:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0xb03fcb83c8a346ff17b2e64243b733dc09b95168ed6cbc0f199546300c9a4633",
              "digest": "CnXtazYL3YL2imDQiWqcWuVTjy6dPRMfG1GNzQaqbkBD",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19 'run-graphql'. lines 97-152:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0xb03fcb83c8a346ff17b2e64243b733dc09b95168ed6cbc0f199546300c9a4633",
              "digest": "CnXtazYL3YL2imDQiWqcWuVTjy6dPRMfG1GNzQaqbkBD",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x12b334a1490aa78edb53ebd57e710e74af0ca7fd5137ea0dfa7e6f041fc11838",
              "digest": "7vS6kQLyLaeC5vuuddni7bGu1A1xKtE6XxDogD5vXrFo",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x19de379c62728af05bb3d71d5ae196e175b82b6daf6e16b1d26d2e9499d6e12a",
              "digest": "8ghEdhN15TtMLU9C3ezSKWMdUxni1NSsAQdquMWCH2jW",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xa460a9aad3b3651a7fb5bba91121f8e7d2e7ba8d5e580cc01a07f7ac9d2f9d8c",
              "digest": "99iTcLWVnneNXZYtMT3vpdNwHLz61pkkkhbsq9z12Ye",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xaa3b8893d3feb5891966197d59fa623a3764f0e21b4c895e26880d5107d5be9f",
              "digest": "FbpXKGjDuJguVtv7Uf5w38M11aBHYn5LLmCDC5CEJp8G",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xca3f1fc99cf64e081d4a3746f625f5ed84f06d942a58a133b92ef96a3492c799",
              "digest": "GSvne9ciWw9KWtpviYbe4nPjhdouNhbikojU2jak5jK2",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xffc4623ba8b1f6132ce4360803087848995901995e302b98f797a62ab996a7cb",
              "digest": "HGs2CgMxwdZq6MFymGfjDZWVYL4SLUzNLvVoYELVnT5G",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20 'run-graphql'. lines 154-170:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
    }
  }
}

task 21 'run-graphql'. lines 172-178:
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22 'run'. lines 180-180:
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 23 'run'. lines 182-182:
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 24 'run'. lines 184-184:
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880
