processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-35:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 37-37:
Checkpoint created: 1

task 3 'run-graphql'. lines 39-87:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IC+3v07UAlJRZe9LVCkxbD/fH7GSax8k79vCuTdSaVP4AQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IEyPKKNGui+F30uB76b47G3g95O8bZSTr6Ss31g4Ncm5AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IOZFFQU7F0cuVWUfUDBa3GURMPjCu4GHEYZVMQZl/Em8AQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IAVW1hzFt8igUhlHaCJXzlOoM39JhVwnfm522iS9lPgYAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x038c2a1b80129ce4d893154d9ca5bf82a9b693535f8088d669cee25acf44c1eb::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "ICsxjA+wrKVObkBMoOY+t+ESY9K+TukPleSCAWIUbidEAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x038c2a1b80129ce4d893154d9ca5bf82a9b693535f8088d669cee25acf44c1eb::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IKGQSoPRrKQpXlmTfKUpCtjparuCITsFpoAFy1N7yiTIAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x038c2a1b80129ce4d893154d9ca5bf82a9b693535f8088d669cee25acf44c1eb::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IEyPKKNGui+F30uB76b47G3g95O8bZSTr6Ss31g4Ncm5AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHgwMzhjMmExYjgwMTI5Y2U0ZDg5MzE1NGQ5Y2E1YmY4MmE5YjY5MzUzNWY4MDg4ZDY2OWNlZTI1YWNmNDRjMWViOjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x038c2a1b80129ce4d893154d9ca5bf82a9b693535f8088d669cee25acf44c1eb::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMzhjMmExYjgwMTI5Y2U0ZDg5MzE1NGQ5Y2E1YmY4MmE5YjY5MzUzNWY4MDg4ZDY2OWNlZTI1YWNmNDRjMWViOjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
