processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 3 'run-graphql'. lines 40-88:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IC8OjOCH4yAEAZFpEG5jU9gSYTkwgAKan0qs/A0hbspfAQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IJ8tvyTe3yO3KoFMcvosmaAcE/y8MSfFNW7VvqlDhFb2AQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IKPaOfpkDAqRELOV29tREAeq44qRY+JekB8LRDuaqROiAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "ID7LYEUKDdRfc0v/F5DHt8ZdFQWUhTXym9Rxopq9IbFAAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x02a6d7a22ed71eff3963f67534f4153619150a9e095cde73672cf8a92208eb97::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IEvfe4HTblkshZfZ8J+tGzUIrCruLTyRw+pamQ5XN95VAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x02a6d7a22ed71eff3963f67534f4153619150a9e095cde73672cf8a92208eb97::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IOw1EeJBHdOQvQl5iZXpVtMIsWxIzP5pr0EVb6gPcEl9AQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x02a6d7a22ed71eff3963f67534f4153619150a9e095cde73672cf8a92208eb97::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IC8OjOCH4yAEAZFpEG5jU9gSYTkwgAKan0qs/A0hbspfAQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHgwMmE2ZDdhMjJlZDcxZWZmMzk2M2Y2NzUzNGY0MTUzNjE5MTUwYTllMDk1Y2RlNzM2NzJjZjhhOTIyMDhlYjk3OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x02a6d7a22ed71eff3963f67534f4153619150a9e095cde73672cf8a92208eb97::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMmE2ZDdhMjJlZDcxZWZmMzk2M2Y2NzUzNGY0MTUzNjE5MTUwYTllMDk1Y2RlNzM2NzJjZjhhOTIyMDhlYjk3OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
