processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 44-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 48-48:
Checkpoint created: 1

task 4 'run-graphql'. lines 50-71:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  159,
                                  45,
                                  191,
                                  36,
                                  222,
                                  223,
                                  35,
                                  183,
                                  42,
                                  129,
                                  76,
                                  114,
                                  250,
                                  44,
                                  153,
                                  160,
                                  28,
                                  19,
                                  252,
                                  188,
                                  49,
                                  39,
                                  197,
                                  53,
                                  110,
                                  213,
                                  190,
                                  169,
                                  67,
                                  132,
                                  86,
                                  246
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988444520"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x9f2dbf24dedf23b72a814c72fa2c99a01c13fcbc3127c5356ed5bea9438456f6",
                          "balance": {
                            "value": "299999988444520"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x97a9f7d8bb9144eecfae2b98e9d31683c2ed2ab170163e5ab373375a09bb9c3d::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  196,
                                  92,
                                  155,
                                  45,
                                  156,
                                  95,
                                  218,
                                  242,
                                  8,
                                  3,
                                  50,
                                  218,
                                  78,
                                  46,
                                  212,
                                  88,
                                  197,
                                  10,
                                  90,
                                  248,
                                  139,
                                  173,
                                  227,
                                  100,
                                  126,
                                  111,
                                  52,
                                  158,
                                  66,
                                  101,
                                  74,
                                  254
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  196,
                                  92,
                                  155,
                                  45,
                                  156,
                                  95,
                                  218,
                                  242,
                                  8,
                                  3,
                                  50,
                                  218,
                                  78,
                                  46,
                                  212,
                                  88,
                                  197,
                                  10,
                                  90,
                                  248,
                                  139,
                                  173,
                                  227,
                                  100,
                                  126,
                                  111,
                                  52,
                                  158,
                                  66,
                                  101,
                                  74,
                                  254
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      196,
                                      92,
                                      155,
                                      45,
                                      156,
                                      95,
                                      218,
                                      242,
                                      8,
                                      3,
                                      50,
                                      218,
                                      78,
                                      46,
                                      212,
                                      88,
                                      197,
                                      10,
                                      90,
                                      248,
                                      139,
                                      173,
                                      227,
                                      100,
                                      126,
                                      111,
                                      52,
                                      158,
                                      66,
                                      101,
                                      74,
                                      254
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xc45c9b2d9c5fdaf2080332da4e2ed458c50a5af88bade3647e6f349e42654afe",
                          "f0": "0xc45c9b2d9c5fdaf2080332da4e2ed458c50a5af88bade3647e6f349e42654afe",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xc45c9b2d9c5fdaf2080332da4e2ed458c50a5af88bade3647e6f349e42654afe"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
