processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-41:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 43-45:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 47-47:
Checkpoint created: 1

task 4 'run-graphql'. lines 49-70:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x8a1a85a7bcfa8f569c83129d8160b89848a1e67efff0cedb962f810c0946ab7a::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  90,
                                  93,
                                  203,
                                  176,
                                  68,
                                  164,
                                  231,
                                  220,
                                  162,
                                  213,
                                  224,
                                  156,
                                  252,
                                  14,
                                  50,
                                  162,
                                  202,
                                  77,
                                  218,
                                  185,
                                  192,
                                  121,
                                  85,
                                  219,
                                  91,
                                  46,
                                  39,
                                  83,
                                  10,
                                  62,
                                  55,
                                  111
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  90,
                                  93,
                                  203,
                                  176,
                                  68,
                                  164,
                                  231,
                                  220,
                                  162,
                                  213,
                                  224,
                                  156,
                                  252,
                                  14,
                                  50,
                                  162,
                                  202,
                                  77,
                                  218,
                                  185,
                                  192,
                                  121,
                                  85,
                                  219,
                                  91,
                                  46,
                                  39,
                                  83,
                                  10,
                                  62,
                                  55,
                                  111
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      90,
                                      93,
                                      203,
                                      176,
                                      68,
                                      164,
                                      231,
                                      220,
                                      162,
                                      213,
                                      224,
                                      156,
                                      252,
                                      14,
                                      50,
                                      162,
                                      202,
                                      77,
                                      218,
                                      185,
                                      192,
                                      121,
                                      85,
                                      219,
                                      91,
                                      46,
                                      39,
                                      83,
                                      10,
                                      62,
                                      55,
                                      111
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x5a5dcbb044a4e7dca2d5e09cfc0e32a2ca4ddab9c07955db5b2e27530a3e376f",
                          "f0": "0x5a5dcbb044a4e7dca2d5e09cfc0e32a2ca4ddab9c07955db5b2e27530a3e376f",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x5a5dcbb044a4e7dca2d5e09cfc0e32a2ca4ddab9c07955db5b2e27530a3e376f"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  230,
                                  69,
                                  21,
                                  5,
                                  59,
                                  23,
                                  71,
                                  46,
                                  85,
                                  101,
                                  31,
                                  80,
                                  48,
                                  90,
                                  220,
                                  101,
                                  17,
                                  48,
                                  248,
                                  194,
                                  187,
                                  129,
                                  135,
                                  17,
                                  134,
                                  85,
                                  49,
                                  6,
                                  101,
                                  252,
                                  73,
                                  188
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988444520"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xe64515053b17472e55651f50305adc651130f8c2bb8187118655310665fc49bc",
                          "balance": {
                            "value": "299999988444520"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
