processed 25 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-29:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 31-31:
Checkpoint created: 1

task 3 'run'. lines 33-33:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'create-checkpoint'. lines 35-35:
Checkpoint created: 2

task 5 'advance-epoch'. lines 37-37:
Epoch advanced: 0

task 6 'run-graphql'. lines 39-55:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 3
    },
    "epoch": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjozLCJ0IjowfQ",
            "node": {
              "digest": "8xZoV7nYZVMgbXfaKk95XiVkaz76HxHrb7oPUJiiwRsi"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjoxfQ",
            "node": {
              "digest": "23st7eoSRaawu6anbhcRkZyCHakjLrThEjkn1CgkuzbQ"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjoyfQ",
            "node": {
              "digest": "4umoYjG8xTW8CuFKG7zpgqNGweBpJ9GNRLNniCvsrzzW"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjozfQ",
            "node": {
              "digest": "EGhE5mvCwfgsLAp4ZpwMqaCGaSpuZy1ZfLo7aTmUNK7F"
            }
          }
        ]
      }
    }
  }
}

task 7 'run'. lines 57-57:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 59-59:
Checkpoint created: 4

task 9 'run'. lines 61-61:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 63-63:
Checkpoint created: 5

task 11 'run'. lines 65-65:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'create-checkpoint'. lines 67-67:
Checkpoint created: 6

task 13 'advance-epoch'. lines 69-69:
Epoch advanced: 1

task 14 'run'. lines 71-71:
created: object(14,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 15 'create-checkpoint'. lines 73-73:
Checkpoint created: 8

task 16 'run'. lines 75-75:
created: object(16,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 17 'create-checkpoint'. lines 77-77:
Checkpoint created: 9

task 18 'run-graphql'. lines 79-118:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 9
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0IjowfQ",
            "node": {
              "digest": "8xZoV7nYZVMgbXfaKk95XiVkaz76HxHrb7oPUJiiwRsi"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0IjoxfQ",
            "node": {
              "digest": "23st7eoSRaawu6anbhcRkZyCHakjLrThEjkn1CgkuzbQ"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0IjoyfQ",
            "node": {
              "digest": "4umoYjG8xTW8CuFKG7zpgqNGweBpJ9GNRLNniCvsrzzW"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0IjozfQ",
            "node": {
              "digest": "EGhE5mvCwfgsLAp4ZpwMqaCGaSpuZy1ZfLo7aTmUNK7F"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0Ijo0fQ",
            "node": {
              "digest": "FFGmro2tVE826c24CTi21e98bSB41rreF2vt3yaYrizr"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo1fQ",
            "node": {
              "digest": "994PsU8LZYvbQdMeRSj45fZsmDR4mop4K75mcHdzDcJW"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo2fQ",
            "node": {
              "digest": "DFPJyETvYTujBTYASiThNS9wubc1LLXQFJatK3Rbkjm1"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo3fQ",
            "node": {
              "digest": "Hk5h5o2DYxmiZ7BFokX3GthTEfh4pzvvPWxFs4RbQ6Qv"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0Ijo4fQ",
            "node": {
              "digest": "61Htcvt9qSde5dJNLrnzhFYCHVw5nE6XeZxAmKLKAdUp"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo5fQ",
            "node": {
              "digest": "65odz3t5jqNPMLrLCJK2FMhoEKXKRB5sKtDmoBvJvNHD"
            }
          }
        ]
      }
    }
  }
}

task 19 'run'. lines 120-120:
created: object(19,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 20 'create-checkpoint'. lines 122-122:
Checkpoint created: 10

task 21 'run-graphql'. lines 124-164:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo0LCJ0IjowfQ",
            "node": {
              "digest": "8xZoV7nYZVMgbXfaKk95XiVkaz76HxHrb7oPUJiiwRsi"
            }
          },
          {
            "cursor": "eyJjIjo0LCJ0IjoxfQ",
            "node": {
              "digest": "23st7eoSRaawu6anbhcRkZyCHakjLrThEjkn1CgkuzbQ"
            }
          },
          {
            "cursor": "eyJjIjo0LCJ0IjoyfQ",
            "node": {
              "digest": "4umoYjG8xTW8CuFKG7zpgqNGweBpJ9GNRLNniCvsrzzW"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo4LCJ0Ijo0fQ",
            "node": {
              "digest": "FFGmro2tVE826c24CTi21e98bSB41rreF2vt3yaYrizr"
            }
          },
          {
            "cursor": "eyJjIjo4LCJ0Ijo1fQ",
            "node": {
              "digest": "994PsU8LZYvbQdMeRSj45fZsmDR4mop4K75mcHdzDcJW"
            }
          },
          {
            "cursor": "eyJjIjo4LCJ0Ijo2fQ",
            "node": {
              "digest": "DFPJyETvYTujBTYASiThNS9wubc1LLXQFJatK3Rbkjm1"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjoxMCwidCI6OH0",
            "node": {
              "digest": "61Htcvt9qSde5dJNLrnzhFYCHVw5nE6XeZxAmKLKAdUp"
            }
          }
        ]
      }
    }
  }
}

task 22 'run-graphql'. lines 166-206:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjozLCJ0IjoxfQ",
            "node": {
              "digest": "23st7eoSRaawu6anbhcRkZyCHakjLrThEjkn1CgkuzbQ"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjoyfQ",
            "node": {
              "digest": "4umoYjG8xTW8CuFKG7zpgqNGweBpJ9GNRLNniCvsrzzW"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjozfQ",
            "node": {
              "digest": "EGhE5mvCwfgsLAp4ZpwMqaCGaSpuZy1ZfLo7aTmUNK7F"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo3LCJ0Ijo1fQ",
            "node": {
              "digest": "994PsU8LZYvbQdMeRSj45fZsmDR4mop4K75mcHdzDcJW"
            }
          },
          {
            "cursor": "eyJjIjo3LCJ0Ijo2fQ",
            "node": {
              "digest": "DFPJyETvYTujBTYASiThNS9wubc1LLXQFJatK3Rbkjm1"
            }
          },
          {
            "cursor": "eyJjIjo3LCJ0Ijo3fQ",
            "node": {
              "digest": "Hk5h5o2DYxmiZ7BFokX3GthTEfh4pzvvPWxFs4RbQ6Qv"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0Ijo5fQ",
            "node": {
              "digest": "65odz3t5jqNPMLrLCJK2FMhoEKXKRB5sKtDmoBvJvNHD"
            }
          }
        ]
      }
    }
  }
}

task 23 'run-graphql'. lines 208-248:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjoyLCJ0IjoyfQ",
            "node": {
              "digest": "4umoYjG8xTW8CuFKG7zpgqNGweBpJ9GNRLNniCvsrzzW"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo2LCJ0Ijo2fQ",
            "node": {
              "digest": "DFPJyETvYTujBTYASiThNS9wubc1LLXQFJatK3Rbkjm1"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": []
      }
    }
  }
}

task 24 'run-graphql'. lines 250-294:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "with_cursor": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo2LCJ0Ijo2fQ",
            "node": {
              "digest": "DFPJyETvYTujBTYASiThNS9wubc1LLXQFJatK3Rbkjm1",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "ICoDUL3dHQdBWRjfdYcaMM5iqBUwyik7XAtePrtkT0JLBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDUtbKItu3PwD080mm+ZZTNf/30rLW/sZsOWFSyVUmZpBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IHyNyGNzdEigWvS1wZNP0dJ5frWNmo22424AImWUhNyyBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJpHVqoJ0xNU4ZvFJZislgJiIHPc21MX6pgGmtwX/jYFBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IPS37m+qfUa8DwlDsjz1hKyl4nqAIiyMUXhMOaMljVPBBgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "without_cursor": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjoxMCwidCI6NH0",
            "node": {
              "digest": "FFGmro2tVE826c24CTi21e98bSB41rreF2vt3yaYrizr",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "ICoDUL3dHQdBWRjfdYcaMM5iqBUwyik7XAtePrtkT0JLCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDUtbKItu3PwD080mm+ZZTNf/30rLW/sZsOWFSyVUmZpCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IHyNyGNzdEigWvS1wZNP0dJ5frWNmo22424AImWUhNyyCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJpHVqoJ0xNU4ZvFJZislgJiIHPc21MX6pgGmtwX/jYFCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJtMt9gbNqQlyMdwuUlGfq6U2aGDb0Wx7ySoZhdiOc9XCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJ37qLMWj0NLmxpirkh3grThddEem5ZNdquTGHb5oqkxCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IMLfxeO0QmAkuqQDl1brlEckF8JNilQCVPCkzfW0rQ4DCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IPS37m+qfUa8DwlDsjz1hKyl4nqAIiyMUXhMOaMljVPBCgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          },
          {
            "cursor": "eyJjIjoxMCwidCI6NX0",
            "node": {
              "digest": "994PsU8LZYvbQdMeRSj45fZsmDR4mop4K75mcHdzDcJW",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "ICoDUL3dHQdBWRjfdYcaMM5iqBUwyik7XAtePrtkT0JLCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDUtbKItu3PwD080mm+ZZTNf/30rLW/sZsOWFSyVUmZpCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IHyNyGNzdEigWvS1wZNP0dJ5frWNmo22424AImWUhNyyCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJpHVqoJ0xNU4ZvFJZislgJiIHPc21MX6pgGmtwX/jYFCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJtMt9gbNqQlyMdwuUlGfq6U2aGDb0Wx7ySoZhdiOc9XCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJ37qLMWj0NLmxpirkh3grThddEem5ZNdquTGHb5oqkxCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IMLfxeO0QmAkuqQDl1brlEckF8JNilQCVPCkzfW0rQ4DCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IPS37m+qfUa8DwlDsjz1hKyl4nqAIiyMUXhMOaMljVPBCgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          },
          {
            "cursor": "eyJjIjoxMCwidCI6Nn0",
            "node": {
              "digest": "DFPJyETvYTujBTYASiThNS9wubc1LLXQFJatK3Rbkjm1",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "ICoDUL3dHQdBWRjfdYcaMM5iqBUwyik7XAtePrtkT0JLCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDUtbKItu3PwD080mm+ZZTNf/30rLW/sZsOWFSyVUmZpCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IHyNyGNzdEigWvS1wZNP0dJ5frWNmo22424AImWUhNyyCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJpHVqoJ0xNU4ZvFJZislgJiIHPc21MX6pgGmtwX/jYFCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJtMt9gbNqQlyMdwuUlGfq6U2aGDb0Wx7ySoZhdiOc9XCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IJ37qLMWj0NLmxpirkh3grThddEem5ZNdquTGHb5oqkxCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IMLfxeO0QmAkuqQDl1brlEckF8JNilQCVPCkzfW0rQ4DCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IPS37m+qfUa8DwlDsjz1hKyl4nqAIiyMUXhMOaMljVPBCgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}
